### PR TITLE
Remove CacheControl

### PR DESCRIPTION
**Pull request by singingwolfboy**
It's just making the bot less reliable. @sarina, can you review this?

### CODE REVIEW

**Comment by nedbat** [comment]
How does CacheControl make the bot less reliable?

**Comment by sarina** [comment]
@nedbat - it doesn't recognize new labels in the repo, and a few other things that I can't remember, but have always been solvable by restarting the bot so it's forced to clear its cache.

:+1:

**Comment by sarina** [comment]
(if this causes other issues we can always revert it)

**Comment by nedbat** [comment]
:+1:

**Pull request merged**
