### PR TITLE
WIP: Rewrite handling of new GitHub PR

### PR DESCRIPTION
**Pull request by gsong**
Convert new GitHub PR into OSPR if appropriate. Also make the right comments on the PR itself as needed.

### CODE REVIEW

**Comment by gsong** [comment]
legacy_hook_handler

**Comment by gsong** [comment]
This was merged by mistake.

**Comment by nedbat** [comment]
@gsong Can you remind me what is left to do on this?

**Comment by nedbat** [comment]
Oh, i had this tab open for weeks, and was looking at the wrong one! Never mind...

**Pull request merged**
