### PR TITLE
Use Sentry instead of Bugsnag

### PR DESCRIPTION
**Pull request by singingwolfboy**
@nedbat @sarina review?

### CODE REVIEW

**Comment by sarina** [comment]
docs/install.rst:14:* `Bugsnag <https://addons.heroku.com/bugsnag>`_

**Comment by sarina** [comment]
I'm OK with this change, but I'd like to hold off on it until we're sure the other changes are working. I'm anxious about merging a complete change to our bug manager at the exact same time we've made major, potentially breaking, changes.

**Comment by singingwolfboy** [comment]
@sarina good catch. I've updated the docs.

I understand the concern about changing the bug manager right now, but the reason I'm doing it is because it simplifies the function signatures (no more passing around a `bugsnag_context` dictionary), which will be important for taking these functions and running them as worker processes. The simpler we can make this code, the less likely it is that anything will go wrong.

**Comment by sarina** [comment]
Hmm well I'm ok if Ned's ok.

**Pull request merged**
